version: "3"
services:
  web:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - "mongo"
    env_file:
      - .env
    volumes:
      - ./src:/app
  
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_password
    ports:
      - 27017:27017
